import { VaultType } from '@/types/hub';

export interface VaultTypeConfig {
  label: string;
  category: 'core' | 'infra' | 'service' | 'optional';
  icon: string;
  color: string;
  badgeBg: string;
  description: string;
  defaultRequired: boolean;
  fields: {
    name: string;
    label: string;
    type: 'text' | 'password' | 'url' | 'date' | 'textarea';
    placeholder?: string;
    required?: boolean;
    helperText?: string;
  }[];
}

export const VAULT_TYPES: Record<VaultType, VaultTypeConfig> = {
  website_admin: {
    label: 'Website Admin Credentials',
    category: 'core',
    icon: 'ShieldCheck',
    color: '#3B82F6',
    badgeBg: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-200 dark:border-blue-900',
    description: 'Admin panel login for WordPress, custom CMS, or dashboard',
    defaultRequired: true,
    fields: [
      { name: 'url', label: 'Admin Login URL', type: 'url', placeholder: 'https://example.com/admin or /wp-admin', required: true },
      { name: 'username', label: 'Admin Username / Email', type: 'text', placeholder: 'admin or info@example.com', required: true },
      { name: 'password', label: 'Admin Password', type: 'password', placeholder: 'Enter password', required: true },
      { name: 'notes', label: 'Role / CMS Details', type: 'textarea', placeholder: 'e.g. Super Admin role, 2FA recovery keys' },
    ],
  },
  business_email: {
    label: 'Business / Client Email',
    category: 'core',
    icon: 'Mail',
    color: '#EA4335',
    badgeBg: 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-200 dark:border-red-900',
    description: 'Webmail, Google Workspace, Titan, or Zoho Mail login',
    defaultRequired: true,
    fields: [
      { name: 'url', label: 'Webmail / Login URL', type: 'url', placeholder: 'https://mail.google.com or webmail link' },
      { name: 'username', label: 'Email Address', type: 'text', placeholder: 'contact@clientdomain.com', required: true },
      { name: 'password', label: 'Email Password', type: 'password', placeholder: 'Enter password', required: true },
      { name: 'notes', label: 'Provider & IMAP/SMTP Notes', type: 'textarea', placeholder: 'Google Workspace / Titan / Zoho / cPanel webmail' },
    ],
  },
  domain: {
    label: 'Domain & Registrar',
    category: 'infra',
    icon: 'Globe',
    color: '#2563EB',
    badgeBg: 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-200 dark:border-sky-900',
    description: 'Domain registration, DNS provider, and renewal info',
    defaultRequired: true,
    fields: [
      { name: 'url', label: 'Domain URL / Registrar Link', type: 'url', placeholder: 'https://godaddy.com or namecheap.com', required: true },
      { name: 'username', label: 'Registrar Login / Owner', type: 'text', placeholder: 'Client GoDaddy / Namecheap account or login email' },
      { name: 'password', label: 'Registrar Password / PIN', type: 'password', placeholder: 'Password or PIN' },
      { name: 'notes', label: 'DNS Records / Nameservers Notes', type: 'textarea', placeholder: 'Cloudflare / Cloudflare DNS / Auto-renewal status' },
    ],
  },
  hosting: {
    label: 'Hosting & Server / cPanel',
    category: 'infra',
    icon: 'Server',
    color: '#7C3AED',
    badgeBg: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-200 dark:border-purple-900',
    description: 'cPanel, Hostinger, AWS, or VPS Hosting dashboard',
    defaultRequired: true,
    fields: [
      { name: 'url', label: 'Hosting Control Panel URL', type: 'url', placeholder: 'https://cpanel.domain.com or hostinger.com', required: true },
      { name: 'username', label: 'Hosting Login Owner / User', type: 'text', placeholder: 'cpanel_user or hosting_email@domain.com', required: true },
      { name: 'password', label: 'Hosting Password', type: 'password', placeholder: 'Enter hosting password' },
      { name: 'notes', label: 'Server IP / Port / Plan Notes', type: 'textarea', placeholder: 'Shared / VPS / Dedicated server details' },
    ],
  },
  github: {
    label: 'GitHub Repository',
    category: 'core',
    icon: 'Github',
    color: '#181717',
    badgeBg: 'bg-slate-500/10 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800',
    description: 'Git repository URL, branch, and access tokens',
    defaultRequired: true,
    fields: [
      { name: 'url', label: 'Repository URL', type: 'url', placeholder: 'https://github.com/ekodrix/client-project', required: true },
      { name: 'username', label: 'GitHub Owner / Org', type: 'text', placeholder: 'ekodrix or client-org' },
      { name: 'access_token', label: 'Personal Access Token / Deploy Key', type: 'password', placeholder: 'ghp_xxxxxxxxxxxx' },
      { name: 'notes', label: 'Branches / CI/CD Notes', type: 'textarea', placeholder: 'Main branch: production, auto-deploy to Vercel' },
    ],
  },
  vercel: {
    label: 'Vercel / Deployment',
    category: 'infra',
    icon: 'Triangle',
    color: '#000000',
    badgeBg: 'bg-zinc-500/10 text-zinc-900 dark:text-zinc-100 border-zinc-200 dark:border-zinc-800',
    description: 'Frontend hosting, production domain, and deploy hooks',
    defaultRequired: true,
    fields: [
      { name: 'url', label: 'Live Deployment URL', type: 'url', placeholder: 'https://project.vercel.app or production domain', required: true },
      { name: 'username', label: 'Vercel Team / Account Owner', type: 'text', placeholder: 'team_ekodrix or client Vercel email' },
      { name: 'api_key', label: 'Deploy Hook / Token', type: 'password', placeholder: 'Vercel token or hook url' },
      { name: 'notes', label: 'Environment Variables / Secrets notes', type: 'textarea', placeholder: 'Production environment notes' },
    ],
  },
  supabase: {
    label: 'Supabase / Database (Optional)',
    category: 'optional',
    icon: 'Database',
    color: '#3ECF8E',
    badgeBg: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-900',
    description: 'Supabase project, Anon key, Service role, and DB connection',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Supabase Project URL', type: 'url', placeholder: 'https://xyzcompany.supabase.co' },
      { name: 'api_key', label: 'Anon Public Key', type: 'password', placeholder: 'eyJh...' },
      { name: 'access_token', label: 'Service Role Key (Secret)', type: 'password', placeholder: 'eyJh...' },
      { name: 'password', label: 'Database Password', type: 'password', placeholder: 'DB connection password' },
      { name: 'notes', label: 'Project Reference ID / Notes', type: 'textarea', placeholder: 'DB schema, storage buckets, auth triggers' },
    ],
  },
  cloudinary: {
    label: 'Cloudinary / Media (Optional)',
    category: 'optional',
    icon: 'Image',
    color: '#3448C5',
    badgeBg: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-200 dark:border-indigo-900',
    description: 'Cloudinary image CDN, upload presets, and API keys',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Cloudinary Console URL', type: 'url', placeholder: 'https://cloudinary.com/console' },
      { name: 'username', label: 'Cloud Name', type: 'text', placeholder: 'e.g. ekodrix-media' },
      { name: 'api_key', label: 'API Key', type: 'text', placeholder: '1234567890' },
      { name: 'password', label: 'API Secret', type: 'password', placeholder: 'Cloudinary API secret' },
      { name: 'notes', label: 'Upload Preset / Folder', type: 'textarea', placeholder: 'Preset: client_uploads, Folder: /products' },
    ],
  },
  razorpay: {
    label: 'Razorpay / Gateway (Optional)',
    category: 'optional',
    icon: 'CreditCard',
    color: '#0C2340',
    badgeBg: 'bg-blue-900/10 text-blue-800 dark:text-blue-300 border-blue-300 dark:border-blue-900',
    description: 'Payment gateway Key ID, Secret, and Webhook secret',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Merchant Dashboard URL', type: 'url', placeholder: 'https://dashboard.razorpay.com' },
      { name: 'api_key', label: 'Key ID (rzp_live_...)', type: 'text', placeholder: 'rzp_live_xxxxxxxx' },
      { name: 'password', label: 'Key Secret', type: 'password', placeholder: 'Secret key' },
      { name: 'access_token', label: 'Webhook Secret', type: 'password', placeholder: 'Webhook verification secret' },
      { name: 'notes', label: 'Merchant Account / KYC Notes', type: 'textarea', placeholder: 'Settlement bank, business type' },
    ],
  },
  server: {
    label: 'Server / VPS (SSH / Root)',
    category: 'infra',
    icon: 'Terminal',
    color: '#FF6B35',
    badgeBg: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-200 dark:border-orange-900',
    description: 'DigitalOcean, AWS EC2, or Linux VPS SSH & sudo access',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Server IP / Host', type: 'text', placeholder: '143.198.xx.xx or vps.domain.com' },
      { name: 'username', label: 'SSH User (root / ubuntu)', type: 'text', placeholder: 'root or ubuntu' },
      { name: 'password', label: 'Password / Sudo Pass', type: 'password', placeholder: 'Enter SSH password' },
      { name: 'ssh_key', label: 'SSH Private / Public Key', type: 'textarea', placeholder: 'ssh-rsa AAAA...' },
      { name: 'notes', label: 'OS & Service Ports', type: 'textarea', placeholder: 'Ubuntu 22.04, Nginx, Port: 22 / 80 / 443' },
    ],
  },
  database: {
    label: 'Standalone Database',
    category: 'infra',
    icon: 'Cylinder',
    color: '#059669',
    badgeBg: 'bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-200 dark:border-teal-900',
    description: 'PostgreSQL, MySQL, MongoDB or Redis connection strings',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Connection URI / Host', type: 'text', placeholder: 'postgresql://user:pass@host:5432/dbname' },
      { name: 'username', label: 'DB User', type: 'text', placeholder: 'db_admin' },
      { name: 'password', label: 'DB Password', type: 'password', placeholder: 'DB password' },
      { name: 'notes', label: 'Database Name & Port', type: 'textarea', placeholder: 'Port 5432 / 3306, SSL mode required' },
    ],
  },
  email_service: {
    label: 'Transactional Email (Resend / SendGrid)',
    category: 'service',
    icon: 'Send',
    color: '#DC2626',
    badgeBg: 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-200 dark:border-rose-900',
    description: 'Resend, SendGrid, Postmark, or Mailgun API keys',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Service Dashboard URL', type: 'url', placeholder: 'https://resend.com' },
      { name: 'api_key', label: 'API Key', type: 'password', placeholder: 're_123456789' },
      { name: 'username', label: 'Verified Sender Email', type: 'text', placeholder: 'noreply@clientdomain.com' },
      { name: 'notes', label: 'Domain DNS Verification notes', type: 'textarea', placeholder: 'DKIM, SPF, DMARC records added' },
    ],
  },
  payment_gateway: {
    label: 'Other Payment Gateway (Stripe/PayPal)',
    category: 'service',
    icon: 'Wallet',
    color: '#6366F1',
    badgeBg: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-200 dark:border-indigo-900',
    description: 'Stripe, PayPal, PhonePe, or PayU credentials',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Gateway Dashboard URL', type: 'url', placeholder: 'https://dashboard.stripe.com' },
      { name: 'api_key', label: 'Publishable / Key ID', type: 'text', placeholder: 'pk_live_...' },
      { name: 'password', label: 'Secret Key', type: 'password', placeholder: 'sk_live_...' },
      { name: 'access_token', label: 'Webhook Signing Secret', type: 'password', placeholder: 'whsec_...' },
      { name: 'notes', label: 'Account Notes', type: 'textarea', placeholder: 'Currency: INR / USD, Webhook endpoints' },
    ],
  },
  analytics: {
    label: 'Analytics & Tracking (GA4 / Meta Pixel)',
    category: 'service',
    icon: 'BarChart',
    color: '#F59E0B',
    badgeBg: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-200 dark:border-amber-900',
    description: 'Google Analytics G-Tag, Meta Pixel ID, Google Search Console',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Analytics Dashboard Link', type: 'url', placeholder: 'https://analytics.google.com' },
      { name: 'api_key', label: 'Measurement ID / Pixel ID', type: 'text', placeholder: 'G-XXXXXXXXXX or Pixel: 123456789' },
      { name: 'username', label: 'Google Account Access', type: 'text', placeholder: 'admin@ekodrix.com' },
      { name: 'notes', label: 'GTM / Search Console details', type: 'textarea', placeholder: 'GTM container ID, Domain verification token' },
    ],
  },
  cloud_storage: {
    label: 'Cloud Storage (AWS S3 / Cloudflare R2)',
    category: 'service',
    icon: 'HardDrive',
    color: '#FF9900',
    badgeBg: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-200 dark:border-orange-900',
    description: 'S3 bucket, R2 access keys, public bucket URL',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Bucket Public URL', type: 'url', placeholder: 'https://pub-xyz.r2.dev or S3 URL' },
      { name: 'username', label: 'Bucket Name / Region', type: 'text', placeholder: 'client-assets-bucket (ap-south-1)' },
      { name: 'api_key', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...' },
      { name: 'password', label: 'Secret Access Key', type: 'password', placeholder: 'Secret key' },
      { name: 'notes', label: 'CORS & Public policy notes', type: 'textarea', placeholder: 'CORS allowed origins' },
    ],
  },
  api_keys: {
    label: 'API Keys & Third Party Tokens',
    category: 'service',
    icon: 'Key',
    color: '#06B6D4',
    badgeBg: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-200 dark:border-cyan-900',
    description: 'Google Maps API, OpenAI, WhatsApp Cloud API keys',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Provider Console URL', type: 'url', placeholder: 'https://console.cloud.google.com' },
      { name: 'username', label: 'Service / Key Name', type: 'text', placeholder: 'Google Maps Places API' },
      { name: 'api_key', label: 'API Key / Token', type: 'password', placeholder: 'AIzaSy...' },
      { name: 'notes', label: 'Restrictions / Quotas', type: 'textarea', placeholder: 'HTTP Referrer restricted to domain' },
    ],
  },
  social_media: {
    label: 'Social Media Accounts',
    category: 'service',
    icon: 'Share2',
    color: '#EC4899',
    badgeBg: 'bg-pink-500/10 text-pink-600 dark:text-pink-400 border-pink-200 dark:border-pink-900',
    description: 'Instagram, Facebook Page, LinkedIn company profiles',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Profile URL', type: 'url', placeholder: 'https://instagram.com/clientbrand' },
      { name: 'username', label: 'Username / Email', type: 'text', placeholder: '@clientbrand' },
      { name: 'password', label: 'Password', type: 'password', placeholder: 'Social account password' },
      { name: 'notes', label: '2FA / Backup details', type: 'textarea', placeholder: 'Linked phone number' },
    ],
  },
  cpanel: {
    label: 'cPanel / Web Hosting',
    category: 'infra',
    icon: 'Settings',
    color: '#F97316',
    badgeBg: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-200 dark:border-orange-900',
    description: 'cPanel login, file manager, and MySQL management',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'cPanel URL (Port 2083)', type: 'url', placeholder: 'https://cpanel.domain.com:2083' },
      { name: 'username', label: 'cPanel Username', type: 'text', placeholder: 'cp_user' },
      { name: 'password', label: 'cPanel Password', type: 'password', placeholder: 'Password' },
      { name: 'notes', label: 'FTP / DB details', type: 'textarea', placeholder: 'FTP host, DB prefix' },
    ],
  },
  ftp: {
    label: 'FTP / SFTP',
    category: 'infra',
    icon: 'Upload',
    color: '#0891B2',
    badgeBg: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-200 dark:border-cyan-900',
    description: 'FTP/SFTP server, port 21/22 and root web directory',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'FTP Host (e.g. ftp.domain.com)', type: 'text', placeholder: 'ftp.domain.com' },
      { name: 'username', label: 'FTP User', type: 'text', placeholder: 'ftp_user' },
      { name: 'password', label: 'FTP Password', type: 'password', placeholder: 'FTP password' },
      { name: 'notes', label: 'Port & Directory (/public_html)', type: 'textarea', placeholder: 'Port 21 or 22 (SFTP), path: /public_html' },
    ],
  },
  cdn: {
    label: 'CDN (Cloudflare / Fastly)',
    category: 'service',
    icon: 'Zap',
    color: '#EAB308',
    badgeBg: 'bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-200 dark:border-yellow-900',
    description: 'Cloudflare SSL, edge caching, and DNS management',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'CDN Dashboard URL', type: 'url', placeholder: 'https://dash.cloudflare.com' },
      { name: 'username', label: 'Account Email', type: 'text', placeholder: 'cdn@ekodrix.com' },
      { name: 'password', label: 'Password / Global API Key', type: 'password', placeholder: 'Enter password or API key' },
      { name: 'notes', label: 'Zone ID / Page Rules', type: 'textarea', placeholder: 'SSL Mode: Full Strict, Always HTTPS on' },
    ],
  },
  monitoring: {
    label: 'Uptime & Error Monitoring (Sentry / UptimeRobot)',
    category: 'service',
    icon: 'Activity',
    color: '#14B8A6',
    badgeBg: 'bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-200 dark:border-teal-900',
    description: 'Sentry DSN, Uptime status monitors, and alert channels',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Monitoring Dashboard', type: 'url', placeholder: 'https://uptimerobot.com or sentry.io' },
      { name: 'api_key', label: 'Sentry DSN / API Key', type: 'password', placeholder: 'https://xxxx@sentry.io/yyyy' },
      { name: 'notes', label: 'Alert Notification Webhook / Email', type: 'textarea', placeholder: 'Alerts sent to dev-team@ekodrix.com' },
    ],
  },
  other: {
    label: 'Other Custom Credentials',
    category: 'optional',
    icon: 'Folder',
    color: '#6B7280',
    badgeBg: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-200 dark:border-slate-800',
    description: 'Any additional credentials or software license keys',
    defaultRequired: false,
    fields: [
      { name: 'url', label: 'Service / Tool URL', type: 'url', placeholder: 'https://example.com' },
      { name: 'username', label: 'Username / ID', type: 'text', placeholder: 'user or license id' },
      { name: 'password', label: 'Password / Key', type: 'password', placeholder: 'Enter password or key' },
      { name: 'notes', label: 'Additional Information', type: 'textarea', placeholder: 'Usage details, renewal notes' },
    ],
  },
};
